<?php

$base = dirname(__DIR__);

$en = include $base.'/lang/en/admin.php';
$ru = include $base.'/lang/ru/admin.php';
$tg = include $base.'/lang/tg/admin.php';

$ruOverrides = [
    'lessons' => 'Уроки',
    'lessons_description' => 'Управление уроками в мобильном приложении.',
    'add_lesson' => 'Добавить урок',
    'lesson_details' => 'Детали урока',
    'lesson_details_hint' => 'Название и описание на английском, русском и таджикском.',
    'lesson_image' => 'Изображение урока',
    'save_lesson' => 'Сохранить урок',
    'update_lesson' => 'Обновить урок',
    'no_lessons_found' => 'Уроки не найдены',
    'search_lessons' => 'Поиск уроков...',
    'news' => 'Новости',
    'news_description' => 'Управление новостями в мобильном приложении.',
    'add_news' => 'Добавить новость',
    'news_details' => 'Детали новости',
    'news_details_hint' => 'Заголовок и описание на английском, русском и таджикском.',
    'news_image' => 'Изображение новости',
    'save_news' => 'Сохранить новость',
    'update_news' => 'Обновить новость',
    'no_news_found' => 'Новости не найдены',
    'search_news' => 'Поиск новостей...',
    'customer_orders' => 'Заказы клиентов',
    'customer_orders_description' => 'Просмотр заказов с итоговой суммой и статусом Elim.',
    'search_orders_placeholder' => 'Поиск по ID заказа, клиенту...',
    'all_platforms' => 'Все платформы',
    'elim_order' => 'Заказ Elim',
    'no_orders_found' => 'Заказы не найдены.',
    'no_elim_order_id' => 'Нет ID заказа Elim',
    'back_to_orders' => 'Назад к заказам',
    'order_number' => 'Заказ #:id',
    'platform_sliders' => 'Слайдеры платформ',
    'platform_categories' => 'Категории платформ',
    'wallet_transactions' => 'Транзакции кошелька',
    'customers' => 'Клиенты',
    'elim_warehouse' => 'Склад Elim',
    'title' => 'Название',
    'title_in' => 'Название (:language)',
    'description_in' => 'Описание (:language)',
    'uploading' => 'Загрузка...',
    'platform_name_in' => 'Название платформы (:language)',
    'category_name_in' => 'Название категории (:language)',
    'logo_in' => 'Логотип (:language)',
    'order_status_name_in' => 'Название статуса (:language)',
    'customers_description' => 'Управление учётными записями и статусом клиентов.',
    'search_customers_placeholder' => 'Поиск клиентов...',
    'joined' => 'Регистрация',
    'unnamed_customer' => 'Клиент без имени',
    'preferred_language' => 'Язык',
    'no_email' => 'Нет email',
    'blocked' => 'Заблокирован',
    'manage_wallet' => 'Управление кошельком',
    'no_customers_found' => 'Клиенты не найдены',
    'no_customers_found_hint' => 'Клиенты появятся здесь после регистрации.',
    'customer_wallet' => 'Кошелёк клиента',
    'back_to_customer' => 'Назад к клиенту',
    'all_transactions' => 'Все транзакции',
    'current_balance' => 'Текущий баланс',
    'add_funds' => 'Пополнить',
    'deduct_balance' => 'Списать',
    'amount_tjs' => 'Сумма (TJS)',
    'wallet_history' => 'История кошелька',
    'balance_after' => 'Баланс после',
    'source' => 'Источник',
    'admin_user' => 'Админ',
    'revert' => 'Отменить',
    'no_wallet_transactions' => 'Транзакций кошелька пока нет.',
    'wallet_transactions_description' => 'Все пополнения, списания и корректировки кошелька.',
    'export_csv' => 'Экспорт CSV',
    'search_wallet_placeholder' => 'Поиск ID, пользователя, телефона...',
    'all_customers' => 'Все клиенты',
    'all_types' => 'Все типы',
    'credit' => 'Пополнение',
    'debit' => 'Списание',
    'all_sources' => 'Все источники',
    'reverted' => 'Отменено',
    'no_transactions_found' => 'Транзакции не найдены.',
    'demo_order' => 'Демо-заказ',
    'sku' => 'SKU',
    'qty' => 'Кол-во',
    'platforms_description' => 'Управление доступными платформами.',
    'platform_translations_logos' => 'Переводы и логотипы платформы',
    'commission_slabs' => 'Комиссионные ступени',
    'no_platforms_found' => 'Платформы не найдены',
    'no_platforms_found_hint' => 'Начните с создания первой платформы.',
    'add_platform' => 'Добавить платформу',
    'edit_platform' => 'Редактировать платформу',
    'platform_details' => 'Детали платформы',
    'platform_details_hint' => 'Введите название и логотип на английском, русском и таджикском.',
    'platform_code' => 'Код платформы',
    'platform_categories_description' => 'Управление категориями маркетплейса для каждой платформы.',
    'is_default' => 'По умолчанию',
    'no_platform_categories_found' => 'Категории платформ не найдены',
    'no_platform_categories_found_hint' => 'Начните с создания первой категории.',
    'add_category' => 'Добавить категорию',
    'add_slab' => 'Добавить ступень',
    'no_commission_slabs_found' => 'Комиссионные ступени не найдены',
    'elim_warehouse_address' => 'Адрес склада Elim',
    'elim_warehouse_address_description' => 'Адрес получателя в Китае для предпросмотра и оформления заказов Elim.',
    'contact_name' => 'Контактное имя',
    'save_warehouse_address' => 'Сохранить адрес склада',
    'search_platforms_placeholder' => 'Поиск платформ...',
    'search_categories_placeholder' => 'Поиск категорий...',
    'code' => 'Код',
    'created' => 'Создано',
    'save_platform' => 'Сохранить платформу',
    'keyword' => 'Ключевое слово',
    'mobile' => 'Мобильный',
    'province' => 'Провинция',
    'area' => 'Район',
    'yes' => 'Да',
    'no' => 'Нет',
];

$tgOverrides = [
    'lessons' => 'Дарсҳо',
    'lessons_description' => 'Идоракунии дарсҳо дар барномаи мобилӣ.',
    'add_lesson' => 'Иловаи дарс',
    'lesson_details' => 'Тафсилоти дарс',
    'lesson_details_hint' => 'Сарлавҳа ва тавсиф ба забонҳои англисӣ, русӣ ва тоҷикӣ.',
    'lesson_image' => 'Тасвири дарс',
    'save_lesson' => 'Захираи дарс',
    'update_lesson' => 'Навсозии дарс',
    'no_lessons_found' => 'Дарс ёфт нашуд',
    'search_lessons' => 'Ҷустуҷӯи дарсҳо...',
    'news' => 'Хабарҳо',
    'news_description' => 'Идоракунии хабарҳо дар барномаи мобилӣ.',
    'add_news' => 'Иловаи хабар',
    'news_details' => 'Тафсилоти хабар',
    'news_details_hint' => 'Сарлавҳа ва тавсиф ба забонҳои англисӣ, русӣ ва тоҷикӣ.',
    'news_image' => 'Тасвири хабар',
    'save_news' => 'Захираи хабар',
    'update_news' => 'Навсозии хабар',
    'no_news_found' => 'Хабар ёфт нашуд',
    'search_news' => 'Ҷустуҷӯи хабарҳо...',
    'customer_orders' => 'Фармоишҳои мизоҷ',
    'customer_orders_description' => 'Дидани фармоишҳо бо маблағи ниҳоӣ ва ҳолати Elim.',
    'search_orders_placeholder' => 'Ҷустуҷӯ аз рӯи ID ё мизоҷ...',
    'all_platforms' => 'Ҳамаи платформаҳо',
    'elim_order' => 'Фармоиши Elim',
    'no_orders_found' => 'Фармоиш ёфт нашуд.',
    'no_elim_order_id' => 'ID-и фармоиши Elim нест',
    'back_to_orders' => 'Бозгашт ба фармоишҳо',
    'order_number' => 'Фармоиш #:id',
    'platform_sliders' => 'Слайдерҳои платформа',
    'platform_categories' => 'Категорияҳои платформа',
    'wallet_transactions' => 'Транзаксияҳои ҳамён',
    'customers' => 'Мизоҷон',
    'elim_warehouse' => 'Анбори Elim',
    'title' => 'Сарлавҳа',
    'title_in' => 'Сарлавҳа (:language)',
    'description_in' => 'Тавсиф (:language)',
    'uploading' => 'Боркунӣ...',
    'platform_name_in' => 'Номи платформа (:language)',
    'category_name_in' => 'Номи категория (:language)',
    'logo_in' => 'Лого (:language)',
    'order_status_name_in' => 'Номи ҳолат (:language)',
    'customers_description' => 'Идоракунии ҳисобҳо ва ҳолати мизоҷон.',
    'search_customers_placeholder' => 'Ҷустуҷӯи мизоҷон...',
    'joined' => 'Аъзо шуд',
    'unnamed_customer' => 'Мизоҷи бе ном',
    'preferred_language' => 'Забон',
    'no_email' => 'Email нест',
    'blocked' => 'Басташуда',
    'manage_wallet' => 'Идоракунии ҳамён',
    'no_customers_found' => 'Мизоҷ ёфт нашуд',
    'no_customers_found_hint' => 'Мизоҷон пас аз бақайдгирӣ дар ин ҷо намоён мешаванд.',
    'customer_wallet' => 'Ҳамёни мизоҷ',
    'back_to_customer' => 'Бозгашт ба мизоҷ',
    'all_transactions' => 'Ҳамаи транзаксияҳо',
    'current_balance' => 'Баланси ҷорӣ',
    'add_funds' => 'Иловаи маблағ',
    'deduct_balance' => 'Кам кардани баланс',
    'amount_tjs' => 'Маблағ (TJS)',
    'wallet_history' => 'Таърихи ҳамён',
    'balance_after' => 'Баланс пас аз',
    'source' => 'Манбаъ',
    'admin_user' => 'Админ',
    'revert' => 'Бозгардонӣ',
    'no_wallet_transactions' => 'Транзаксияҳои ҳамён ҳанӯз нест.',
    'wallet_transactions_description' => 'Ҳамаи пуркунӣ, харҷот ва танзимоти ҳамёни мизоҷон.',
    'export_csv' => 'Содироти CSV',
    'search_wallet_placeholder' => 'Ҷустуҷӯи ID, корбар, телефон...',
    'all_customers' => 'Ҳамаи мизоҷон',
    'all_types' => 'Ҳамаи намудҳо',
    'credit' => 'Пуркунӣ',
    'debit' => 'Харҷот',
    'all_sources' => 'Ҳамаи манбаъҳо',
    'reverted' => 'Бозгардонда шуд',
    'no_transactions_found' => 'Транзаксия ёфт нашуд.',
    'demo_order' => 'Фармоиши демо',
    'sku' => 'SKU',
    'qty' => 'Миқдор',
    'platforms_description' => 'Идоракунии платформаҳои дастрас.',
    'platform_translations_logos' => 'Тарҷумаҳо ва логоҳои платформа',
    'commission_slabs' => 'Сатҳҳои комиссия',
    'no_platforms_found' => 'Платформа ёфт нашуд',
    'no_platforms_found_hint' => 'Аз эҷоди аввалин платформа оғоз кунед.',
    'add_platform' => 'Иловаи платформа',
    'edit_platform' => 'Таҳрири платформа',
    'platform_details' => 'Тафсилоти платформа',
    'platform_details_hint' => 'Ном ва лого ба забонҳои англисӣ, русӣ ва тоҷикӣ.',
    'platform_code' => 'Рамзи платформа',
    'platform_categories_description' => 'Идоракунии категорияҳои бозор барои ҳар платформа.',
    'is_default' => 'Пешфарз',
    'no_platform_categories_found' => 'Категорияҳои платформа ёфт нашуд',
    'no_platform_categories_found_hint' => 'Аз эҷоди аввалин категория оғоз кунед.',
    'add_category' => 'Иловаи категория',
    'add_slab' => 'Иловаи сатҳ',
    'no_commission_slabs_found' => 'Сатҳҳои комиссия ёфт нашуд',
    'elim_warehouse_address' => 'Суроғаи анбори Elim',
    'elim_warehouse_address_description' => 'Суроғаи қабулкунанда дар Чин барои пешнамоиш ва checkout-и Elim.',
    'contact_name' => 'Номи тамос',
    'save_warehouse_address' => 'Захираи суроғаи анбор',
    'search_platforms_placeholder' => 'Ҷустуҷӯи платформаҳо...',
    'search_categories_placeholder' => 'Ҷустуҷӯи категорияҳо...',
    'code' => 'Рамз',
    'created' => 'Эҷод шуд',
    'save_platform' => 'Захираи платформа',
    'keyword' => 'Калимаи калидӣ',
    'mobile' => 'Мобилӣ',
    'province' => 'Вилоят',
    'area' => 'Ноҳия',
    'yes' => 'Ҳа',
    'no' => 'Не',
];

$mergedRu = array_merge($en, $ru, $ruOverrides);
$mergedTg = array_merge($en, $tg, $tgOverrides);

ksort($mergedRu);
ksort($mergedTg);

writeLangFile($base.'/lang/ru/admin.php', $mergedRu);
writeLangFile($base.'/lang/tg/admin.php', $mergedTg);

echo 'Synced ru: '.count($mergedRu).' keys, tg: '.count($mergedTg)." keys\n";

function writeLangFile(string $path, array $lines): void
{
    $content = "<?php\n\nreturn [\n";

    foreach ($lines as $key => $value) {
        $content .= '    '.var_export($key, true).' => '.var_export($value, true).",\n";
    }

    $content .= "];\n";

    file_put_contents($path, $content);
}
